#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/Repository
#开启文件上传功能
  servlet:
     multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
#整合mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.repositories.dao.User
#文件下载路径
file.path: D:/work/fileTest
#关闭mybatis-plus自动将下划线转化为驼峰形式
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
